name: Get Citation Data

on:
  push:
    branches: ["master"]
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Specify the Python version you need for your project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./google_scholar_crawler/requirements.txt

      - name: Run Script
        run: |
          python ./google_scholar_crawler/main.py
        env:
          GOOGLE_SCHOLAR_ID: ABMEJV8AAAAJ

      - name: Commit and Push Results
        run: |
          cd ./results
          git init
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add *.json
          git commit -m "Updated Citation Data."
          git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:google-scholar-stats --force
